spring:
  main:
    allow-bean-definition-overriding : true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_rest_jpa_db
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
springrestjpa:
  rabbitmq:
    queue: async.test.queue
    exchange: async.test.exchange
    routingkey: async.test.routingkey
